---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk
inputs:
  - name: repo
  - name: sbt-ivy-cache
run:
  path: sh
  args:
    - repo/ci/tasks/deploy-to-kube.sh
