---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: getourneau/alpine-bash-git
outputs:
  - name: out
run:
  path: /bin/bash
  args:
  - repo-release/ci/tasks/merge-branch.sh
