---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: 1science/sbt
inputs:
  - name: repo
  - name: sbt-ivy-cache
run:
  dir: repo
  path: sh
  args:
    - repo/ci/tasks/unit.sh
